# Generated by Django 2.2.2 on 2019-06-28 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookInstanc',
            new_name='BookInstance',
        ),
    ]
